[32mINFO    [0m Utility.customLogger:test_invalidLogin.py:36 ***********TC_007 Verifying Invalid Login Test***********
[32mINFO    [0m Utility.customLogger:test_invalidLogin.py:37 ****Started Login Test****
[32mINFO    [0m Utility.customLogger:test_invalidLogin.py:46 ****Invalid Login test passed ****